{% set name = "segmentation-models-pytorch" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/segmentation_models_pytorch-{{ version }}.tar.gz
  sha256: 8e00ed1707698d309d23f207aef15f21465e091aa0f1dc8043ec3300f5f67216

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - efficientnet-pytorch ==0.6.3
    - pretrainedmodels ==0.7.4
    - timm ==0.4.12
    - torchvision >=0.5.0

test:
  imports:
    - segmentation_models_pytorch
    - segmentation_models_pytorch.base
    - segmentation_models_pytorch.encoders
    - segmentation_models_pytorch.fpn
    - segmentation_models_pytorch.linknet
    - segmentation_models_pytorch.pspnet
    - segmentation_models_pytorch.unet
    - segmentation_models_pytorch.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qubvel/segmentation_models.pytorch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Image segmentation models with pre-trained backbones. PyTorch.
  dev_url: https://github.com/qubvel/segmentation_models.pytorch

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
    - ocefpaf
